<?php

$universities_array = [
  // "" => ["name" =>"", "state" => ""],
  "aaua" => ["name" =>"Adekunle Ajasin University", "state" => "Ondo"],
  "absu" => ["name" =>"Abia State University", "state" => "Abia"],
  "jabu" => ["name" =>"Joseph Ayo Babalola University", "state" => "Osun"],
  "run" => ["name" =>"Redeemer's University Nigeria", "state" => "Osun"],
  "abuad" => ["name" =>"Afe Babalola University", "state" => "Ekiti"],
  "aksu" => ["name" =>"Akwa Ibom State University", "state" => "Akwa Ibom"],
  "aun" => ["name" =>"American University of Nigeria", "state" => "Adamawa"],
  "atbu" => ["name" =>"Abubakar Tafawa Balewa University", "state" => "Bauchi"],
  "adsu" => ["name" =>"Adamawa State University", "state" => "Adamawa"],
  "ac" => ["name" =>"Achievers University", "state" => "Ondo"],
  "abu" => ["name" =>"Ahmadu Bello University", "state" => "Kaduna"],
  "ahu" => ["name" =>"Al-Hikmah University", "state" => "Kwara"],
  "ansu" => ["name" =>"Anambra State University", "state" => "Anambra"],
  "acu" => ["name" =>"Ajayi Crowther University", "state" => "Oyo"],
  "buk" => ["name" =>"Bayero University", "state" => "Kano"],
  "bu" => ["name" =>"Babcock University", "state" => "Ogun"],
  "but" => ["name" =>"Bells University of Technology", "state" => "Ogun"],
  "biu" => ["name" =>"Benson Idahosa University", "state" => "Edo"],
  "bsu" => ["name" =>"Benue State University", "state" => "Benue"],
  "ebu" => ["name" =>"ECWA Bingham University", "state" => "Nassarawa"],
  "bowen-uni" => ["name" =>"Bowen University", "state" => "Osun"],
  "ysu" => ["name" =>"Bukar Abba Ibrahim University", "state" => "Yobe"],
  "cetep-city-uni" => ["name" =>"CETEP City University", "state" => "Lagos"],
  "caleb-uni" => ["name" =>"Caleb University", "state" => "Lagos"],
  "caritas-uni" => ["name" =>"Caritas University", "state" => "Enugu"],
  "city-uni" => ["name" =>"City University", "state" => "Lagos"],
  "noun" => ["name" =>"National Open University of Nigeria", "state" => "Lagos"],
  "cut" => ["name" =>"City University of Technology", "state" => "Kaduna"],
  "covenant-uni" => ["name" =>"Covenant University", "state" => "Ogun"],
  "crawford-uni" => ["name" =>"Crawford University", "state" => "Ogun"],
  "crescent-uni" => ["name" =>"Crescent University", "state" => "Ogun"],
  "crutech" => ["name" =>"Cross River University of Technology", "state" => "Cross River"],
  "delsu" => ["name" =>"Delta State University, Abraka", "state" => "Delta"],
  "ebsu" => ["name" =>"Ebonyi State University", "state" => "Ebonyi"],
  "evangel-uni" => ["name" =>"Evangel University, Akaeze", "state" => "Ebonyi"],
  "elizade-uni" => ["name" =>"Elizade University", "state" => "Ondo"],
  "fuo" => ["name" =>"Fountain University, Osogbo", "state" => "Osun"],
  "fudm" => ["name" =>"Federal University, Dutsin-Ma", "state" => "Katsina"],
  "futa" => ["name" =>"Federal University of Technology Akure", "state" => "Ondo"],
  "funai" => ["name" =>"Federal University Ndufe Alike, Ikwo", "state" => "Ebonyi"],
  "gregory-uni" => ["name" =>"Gregory University", "state" => "Abia"],
  "gou" => ["name" =>"Godfrey Okoye University", "state" => "Enugu"],
  "iuo" => ["name" =>"Igbinedion University", "state" => "Edo"],
  "koladaisi-uni" => ["name" =>"Koladaisi University", "state" => "Oyo"],
  "oui" => ["name" =>"Oduduwa University", "state" => "Osun"],
  "lu" => ["name" =>"Landmark University", "state" => "Kwara"],
  "mciu" => ["name" =>"Michael and Cecilia Ibru University", "state" => "Delta"],
  "lasu" => ["name" =>"Lagos State University", "state" => "Lagos"],
  "ntnu" => ["name" =>"Nigerian Turkish Nile University", "state" => "Abuja(FCT)"],
  "tsu" => ["name" =>"Taraba State University", "state" => "Taraba"],
  "uniben" => ["name" =>"University of Benin", "state" => "Edo"],
  "unical" => ["name" =>"University of Calabar", "state" => "Cross River"],
  "ui" => ["name" =>"University of Ibadan", "state" => "Oyo"],
  "umyu" => ["name" =>"Umaru Musa Yar'adua University Katsina", "state" => "Katsina"],
  "unilag" => ["name" =>"University of Lagos", "state" => "Lagos"],
  "uniport" => ["name" =>"University of Port Harcourt", "state" => "Rivers"],
  "unn" => ["name" =>"University of Nigeria, Nsukka", "state" => "Enugu"],
  "vuna" => ["name" =>"Veritas University (Catholic University of Nigeria) Abuja", "state" => "Abuja(FCT)"],
  "uniilorin" => ["name" =>"University of Ilorin", "state" => "Kwara"],

];


?>
